Refactor release process: add Maven `release` profile, reorganize plugins, and adjust workflows.

diff --git a/.github/workflows/maven_release-testing.yml b/.github/workflows/maven_release-testing.yml
--- a/.github/workflows/maven_release-testing.yml
+++ b/.github/workflows/maven_release-testing.yml
@@ -38,7 +38,7 @@ jobs:
 
       - name: Prepare Release
         run: |
-          mvn versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}
+          mvn versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }} -Pdefault
           git commit -am "Prepare release ${{ github.event.inputs.releaseVersion }}"
           git tag -a v${{ github.event.inputs.releaseVersion }} -m "Release v${{ github.event.inputs.releaseVersion }}"
 
@@ -48,21 +48,21 @@ jobs:
           mkdir -p ~/.m2
           cp .github/settings.xml ~/.m2/settings.xml
 
-      - name: Import GPG key
-        run: |
-          # Create a temporary file for the key
-          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private_key.asc
-          # Import the key with proper permissions
-          gpg --batch --import private_key.asc
-          # Clean up
-          rm private_key.asc
-          # Trust the key
-          echo -e "5\ny\n" | gpg --batch --command-fd 0 --expert --edit-key $(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2) trust
-          # Verify the key is imported
-          gpg --list-secret-keys --keyid-format LONG
+#      - name: Import GPG key
+#        run: |
+#          # Create a temporary file for the key
+#          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private_key.asc
+#          # Import the key with proper permissions
+#          gpg --batch --import private_key.asc
+#          # Clean up
+#          rm private_key.asc
+#          # Trust the key
+#          echo -e "5\ny\n" | gpg --batch --command-fd 0 --expert --edit-key $(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2) trust
+#          # Verify the key is imported
+#          gpg --list-secret-keys --keyid-format LONG
 
       - name: Deploy to Maven Central
-        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} clean deploy
+        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} clean deploy -Prelease
         env:
           OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
           OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
@@ -70,7 +70,7 @@ jobs:
 
       - name: Prepare for Next Development Version
         run: |
-          mvn versions:set -DnewVersion=${{ github.event.inputs.nextVersion }}
+          mvn versions:set -DnewVersion=${{ github.event.inputs.nextVersion }} -Pdefault
           git commit -am "Prepare for next development iteration: ${{ github.event.inputs.nextVersion }}"
 
       - name: Push Changes
